spring:
  application:
    name: recipes-api
  data:
    mongodb:
      spring.mongo.uri: mongodb://localhost:27017/RecipesDb

server:
  port: 6000

jwt:
  issuer: Auth.api
  audience: Homesite
  secret: placeholder_jwt_key_for_development

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
