spring:
  application:
    name: recipes-api
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/RecipesDb}

server:
  port: 6000

jwt:
  issuer: ${ISSUER:Auth.api}
  audience: ${JWT_AUDIENCE:Homesite}
  key: ${JWT_KEY:placeholder_jwt_key_for_development}

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
